<Project>
	<PropertyGroup>
		<Version>1.2.0</Version>
		<AssemblyVersion>1.2.0.0</AssemblyVersion>
		<FileVersion>1.2.0.0</FileVersion>
		<InformationalVersion>1.2.0</InformationalVersion>
		<Product>ZabbixTrayMonitor</Product>
		<Description>Zabbix Tray Monitor</Description>
		<Company>Darano94</Company>
		<Authors>Darano94</Authors>
		<Copyright>Copyright © 2026</Copyright>
	</PropertyGroup>
</Project>